BASE_PROJ ?= $(shell pwd)
LINUX ?= ${BASE_PROJ}/linux
RUNTIME_IMAGE ?= zhengjie-dual-vm
SSH_PORT ?= "51022"
NET_PORT ?= "51023"
GDB_PORT ?= "1210"
DUAL_VM_SCRIPT ?= ${BASE_PROJ}/scripts/dual-vm.sh
DUAL_VM1_SSH_PORT ?= "53022"
DUAL_VM1_NET_PORT ?= "53023"
DUAL_VM1_GDB_PORT ?= "1311"
DUAL_VM2_SSH_PORT ?= "53122"
DUAL_VM2_NET_PORT ?= "53123"
DUAL_VM2_GDB_PORT ?= "1312"
DUAL_VM3_SSH_PORT ?= "53222"
DUAL_VM3_NET_PORT ?= "53223"
DUAL_VM3_GDB_PORT ?= "1313"
DUAL_VM4_SSH_PORT ?= "53322"
DUAL_VM4_NET_PORT ?= "53323"
DUAL_VM4_GDB_PORT ?= "1314"
DUAL_VM1_HOST_CPUSET ?= auto
DUAL_VM2_HOST_CPUSET ?= auto
DUAL_VM3_HOST_CPUSET ?= auto
DUAL_VM4_HOST_CPUSET ?= auto
DUAL_VM1_MEMORY_MB ?= 4096
DUAL_VM2_MEMORY_MB ?= 4096
DUAL_VM3_MEMORY_MB ?= 4096
DUAL_VM4_MEMORY_MB ?= 4096
DUAL_VM1_VCPUS ?= 4
DUAL_VM2_VCPUS ?= 4
DUAL_VM3_VCPUS ?= 4
DUAL_VM4_VCPUS ?= 4
KTRACK ?= ${BASE_PROJ}/tools/kernel-track/ktrack.sh
EXP1_SCRIPT_DIR ?= ${BASE_PROJ}/scripts/exp1
EXP1_KATRAN_BUILD_SCRIPT ?= ${BASE_PROJ}/scripts/exp1/build-katran.sh
EXP1_MODE ?= both
EXP1_WORKLOADS ?= both
EXP1_WRK_CONNECTIONS ?= 1 2 4 8 16 32 64 128 256
EXP1_WRK_THREADS ?= 4
EXP1_WRK_WARMUP ?= 15
EXP1_WRK_DURATION ?= 60
EXP1_WRK_REPEATS ?= 5
EXP1_NGINX_CPUSET ?= 0-3
EXP1_WRK_CPUSET ?= 0-3
EXP1_WRK2_RATES ?= 50000 100000 150000 200000 250000 300000 350000 400000 450000 500000
EXP1_WRK2_THREADS ?= 4
EXP1_WRK2_CONNECTIONS ?= 256
EXP1_WRK2_WARMUP ?= 15
EXP1_WRK2_DURATION ?= 60
EXP1_WRK2_REPEATS ?= 5
EXP1_WRK2_CPUSET ?= 0-3
EXP1_WRK2_BIN ?= wrk2
EXP1_WRK2_AUTO_BUILD ?= 1
EXP1_HTTPERF_CPUSET ?= 0-3
EXP1_HTTPERF_RATES ?= 5000 10000 20000 40000 80000 120000 160000 200000
EXP1_HTTPERF_WARMUP ?= 15
EXP1_HTTPERF_DURATION ?= 60
EXP1_HTTPERF_REPEATS ?= 5
EXP1_HTTPERF_TIMEOUT ?= 5
EXP1_HTTPERF_CLIENT_VMS ?= vm2
EXP1_HTTPERF_WORKERS_PER_VM ?= 1
EXP1_HTTPERF_ULIMIT_NOFILE ?= off
EXP1_KATRAN_CPUSET ?= 0-3
EXP1_KATRAN_VIP ?= 192.168.100.100
EXP1_KATRAN_GRPC_PORT ?= 50051
EXP1_KATRAN_DEFAULT_MAC ?= 52:54:00:aa:00:22
EXP1_KATRAN_FORWARDING_CORES ?= 0,1,2,3
EXP1_KATRAN_LRU_SIZE ?= 1000000
EXP1_KATRAN_SERVER_BIN ?= /linux-dev-env/source/katran/_build/build/example_grpc/katran_server_grpc
EXP1_KATRAN_BPF_OBJ ?= /linux-dev-env/source/katran/_build/deps/bpfprog/bpf/balancer.bpf.o
EXP1_KATRAN_GOCLIENT_BIN ?= /linux-dev-env/source/katran/example_grpc/goclient/src/katranc/main/main
EXP1_KATRAN_LIB_DIRS ?= /linux-dev-env/source/katran/_build/deps/lib:/linux-dev-env/source/katran/_build/deps/lib64
EXP1_KATRAN_AUTO_BUILD ?= 1
EXP1_KATRAN_REQUIRED_BPF_DEFINE ?= LOCAL_DELIVERY_OPTIMIZATION
EXP1_KATRAN_LOCAL_DELIVERY_FLAGS ?= 1
EXP1_KATRAN_FORCE_REBUILD ?= 0
EXP1_KATRAN_INSTALL_BUILD_DEPS ?= 1
EXP1_RUN_DIR ?=
EXP2_SCRIPT_DIR ?= ${BASE_PROJ}/scripts/exp2
EXP2_RESULTS_BASE ?= ${BASE_PROJ}/results/exp2/discovery
EXP2_STAGEA_WORKLOAD ?= wrk2
EXP2_STAGEA_WORKLOADS ?= wrk wrk2
EXP2_STAGEA_WRK_CONNECTIONS ?= 256
EXP2_STAGEA_WRK_THREADS ?= 4
EXP2_STAGEA_WRK2_RATE ?= 250000
EXP2_STAGEA_WRK2_CONNECTIONS ?= 256
EXP2_STAGEA_WRK2_THREADS ?= 4
EXP2_STAGEA_WORKLOAD_WARMUP_SECS ?= 5
EXP2_STAGEA_MEASURE_TAIL_SECS ?= 120
EXP2_STAGEA_STEADY_WARMUP_SECS ?= 30
EXP2_STAGEA_SAMPLE_INTERVAL_SECS ?= 30
EXP2_STAGEA_SAMPLE_COUNT ?= 10
EXP2_STAGEA_MAPS ?= all
EXP2_STAGEA_BALANCER_PROG_NAME ?= balancer_ingress
EXP2_STAGEA_MAX_MAP_DUMP_ENTRIES ?= 1000000
EXP2_STAGEA_SKIP_LARGE_MAP_DUMPS ?= 1
EXP2_STAGEA_KEEP_INVARIANT_HASH_ONLY_DUMP ?= 1
EXP2_STAGEA_SKIP_INSTALL ?= 0
EXP2_ORACLE_RESULTS_BASE ?= ${BASE_PROJ}/results/exp2/oracle
EXP2_ORACLE_SPEC ?=
EXP2_ORACLE_RING_SIZE ?= 65537
EXP2_ORACLE_GENERATED_HEADER ?= ${BASE_PROJ}/source/katran/katran/lib/bpf/oracle/exp2_oracle_handwritten.h
EXP2_ORACLE_KATRAN_SRC_DIR ?= ${BASE_PROJ}/source/katran
EXP2_ORACLE_KATRAN_BUILD_DIR ?= ${BASE_PROJ}/source/katran/_build_exp2_oracle
EXP2_ORACLE_BPF_DEFINES ?= -DLOCAL_DELIVERY_OPTIMIZATION -DEXP2_ORACLE_CH_RINGS
EXP2_ORACLE_FORCE_REBUILD ?= 0
EXP2_ORACLE_SKIP_BUILD ?= 0
EXP2_EVAL_RESULTS_BASE ?= ${BASE_PROJ}/results/exp2/eval
EXP2_EVAL_ORACLE_ENV ?=
EXP2_EVAL_RUN_ID ?=
EXP2_EVAL_ARCHIVE_OLD ?= 1
EXP2_EVAL_VANILLA_KATRAN_AUTO_BUILD ?= 1
EXP2_EVAL_OPT_KATRAN_AUTO_BUILD ?= 0
EXP2_EVAL4_RESULTS_BASE ?= ${BASE_PROJ}/results/exp2/eval-fourway
EXP2_EVAL4_ORACLE_ENV ?=
EXP2_EVAL4_RUN_ID ?=
EXP2_EVAL4_ARCHIVE_OLD ?= 1
EXP2_EVAL4_VANILLA_KATRAN_AUTO_BUILD ?= 1
EXP2_EVAL4_OPT_KATRAN_AUTO_BUILD ?= 0
EXP2_EVAL4_CLIENT_VM ?= vm1
EXP2_EVAL4_LB_VM ?= vm2
EXP2_EVAL4_BACKEND_VM ?= vm3
EXP2_EVAL4_BACKEND_IP ?=
EXP2_EVAL4_FORWARD_VIP ?= 192.168.100.100
EXP2_EVAL4_KATRAN_VIP ?= ${EXP2_EVAL4_FORWARD_VIP}
EXP2_EVAL4_KATRAN_DEFAULT_MAC ?=
.ALWAYS:

all: vmlinux

docker: .ALWAYS
	docker buildx build --network=host --progress=plain -t $(RUNTIME_IMAGE) .

qemu-run: 
	docker run --privileged --rm \
	--device=/dev/kvm:/dev/kvm \
	-v ${BASE_PROJ}:/linux-dev-env -v ${LINUX}:/linux \
	-w /linux \
	-p 127.0.0.1:${SSH_PORT}:52222 \
	-p 127.0.0.1:${NET_PORT}:52223 \
	-p 127.0.0.1:${GDB_PORT}:1234 \
	-it $(RUNTIME_IMAGE):latest \
	/linux-dev-env/q-script/yifei-q -s

# connect running qemu by ssh
qemu-ssh:
	ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -t root@127.0.0.1 -p ${SSH_PORT}

dual-vm1:
	LINUX_DIR=${LINUX} RUNTIME_IMAGE=$(RUNTIME_IMAGE) \
	DUAL_VM1_SSH_PORT=${DUAL_VM1_SSH_PORT} DUAL_VM1_NET_PORT=${DUAL_VM1_NET_PORT} DUAL_VM1_GDB_PORT=${DUAL_VM1_GDB_PORT} \
	DUAL_VM2_SSH_PORT=${DUAL_VM2_SSH_PORT} DUAL_VM2_NET_PORT=${DUAL_VM2_NET_PORT} DUAL_VM2_GDB_PORT=${DUAL_VM2_GDB_PORT} \
	DUAL_VM3_SSH_PORT=${DUAL_VM3_SSH_PORT} DUAL_VM3_NET_PORT=${DUAL_VM3_NET_PORT} DUAL_VM3_GDB_PORT=${DUAL_VM3_GDB_PORT} \
	DUAL_VM4_SSH_PORT=${DUAL_VM4_SSH_PORT} DUAL_VM4_NET_PORT=${DUAL_VM4_NET_PORT} DUAL_VM4_GDB_PORT=${DUAL_VM4_GDB_PORT} \
	DUAL_VM1_HOST_CPUSET=${DUAL_VM1_HOST_CPUSET} DUAL_VM2_HOST_CPUSET=${DUAL_VM2_HOST_CPUSET} DUAL_VM3_HOST_CPUSET=${DUAL_VM3_HOST_CPUSET} DUAL_VM4_HOST_CPUSET=${DUAL_VM4_HOST_CPUSET} \
	DUAL_VM1_MEMORY_MB=${DUAL_VM1_MEMORY_MB} DUAL_VM2_MEMORY_MB=${DUAL_VM2_MEMORY_MB} DUAL_VM3_MEMORY_MB=${DUAL_VM3_MEMORY_MB} DUAL_VM4_MEMORY_MB=${DUAL_VM4_MEMORY_MB} \
	DUAL_VM1_VCPUS=${DUAL_VM1_VCPUS} DUAL_VM2_VCPUS=${DUAL_VM2_VCPUS} DUAL_VM3_VCPUS=${DUAL_VM3_VCPUS} DUAL_VM4_VCPUS=${DUAL_VM4_VCPUS} \
	${DUAL_VM_SCRIPT} start vm1

dual-vm2:
	LINUX_DIR=${LINUX} RUNTIME_IMAGE=$(RUNTIME_IMAGE) \
	DUAL_VM1_SSH_PORT=${DUAL_VM1_SSH_PORT} DUAL_VM1_NET_PORT=${DUAL_VM1_NET_PORT} DUAL_VM1_GDB_PORT=${DUAL_VM1_GDB_PORT} \
	DUAL_VM2_SSH_PORT=${DUAL_VM2_SSH_PORT} DUAL_VM2_NET_PORT=${DUAL_VM2_NET_PORT} DUAL_VM2_GDB_PORT=${DUAL_VM2_GDB_PORT} \
	DUAL_VM3_SSH_PORT=${DUAL_VM3_SSH_PORT} DUAL_VM3_NET_PORT=${DUAL_VM3_NET_PORT} DUAL_VM3_GDB_PORT=${DUAL_VM3_GDB_PORT} \
	DUAL_VM4_SSH_PORT=${DUAL_VM4_SSH_PORT} DUAL_VM4_NET_PORT=${DUAL_VM4_NET_PORT} DUAL_VM4_GDB_PORT=${DUAL_VM4_GDB_PORT} \
	DUAL_VM1_HOST_CPUSET=${DUAL_VM1_HOST_CPUSET} DUAL_VM2_HOST_CPUSET=${DUAL_VM2_HOST_CPUSET} DUAL_VM3_HOST_CPUSET=${DUAL_VM3_HOST_CPUSET} DUAL_VM4_HOST_CPUSET=${DUAL_VM4_HOST_CPUSET} \
	DUAL_VM1_MEMORY_MB=${DUAL_VM1_MEMORY_MB} DUAL_VM2_MEMORY_MB=${DUAL_VM2_MEMORY_MB} DUAL_VM3_MEMORY_MB=${DUAL_VM3_MEMORY_MB} DUAL_VM4_MEMORY_MB=${DUAL_VM4_MEMORY_MB} \
	DUAL_VM1_VCPUS=${DUAL_VM1_VCPUS} DUAL_VM2_VCPUS=${DUAL_VM2_VCPUS} DUAL_VM3_VCPUS=${DUAL_VM3_VCPUS} DUAL_VM4_VCPUS=${DUAL_VM4_VCPUS} \
	${DUAL_VM_SCRIPT} start vm2

dual-vm3:
	LINUX_DIR=${LINUX} RUNTIME_IMAGE=$(RUNTIME_IMAGE) \
	DUAL_VM1_SSH_PORT=${DUAL_VM1_SSH_PORT} DUAL_VM1_NET_PORT=${DUAL_VM1_NET_PORT} DUAL_VM1_GDB_PORT=${DUAL_VM1_GDB_PORT} \
	DUAL_VM2_SSH_PORT=${DUAL_VM2_SSH_PORT} DUAL_VM2_NET_PORT=${DUAL_VM2_NET_PORT} DUAL_VM2_GDB_PORT=${DUAL_VM2_GDB_PORT} \
	DUAL_VM3_SSH_PORT=${DUAL_VM3_SSH_PORT} DUAL_VM3_NET_PORT=${DUAL_VM3_NET_PORT} DUAL_VM3_GDB_PORT=${DUAL_VM3_GDB_PORT} \
	DUAL_VM4_SSH_PORT=${DUAL_VM4_SSH_PORT} DUAL_VM4_NET_PORT=${DUAL_VM4_NET_PORT} DUAL_VM4_GDB_PORT=${DUAL_VM4_GDB_PORT} \
	DUAL_VM1_HOST_CPUSET=${DUAL_VM1_HOST_CPUSET} DUAL_VM2_HOST_CPUSET=${DUAL_VM2_HOST_CPUSET} DUAL_VM3_HOST_CPUSET=${DUAL_VM3_HOST_CPUSET} DUAL_VM4_HOST_CPUSET=${DUAL_VM4_HOST_CPUSET} \
	DUAL_VM1_MEMORY_MB=${DUAL_VM1_MEMORY_MB} DUAL_VM2_MEMORY_MB=${DUAL_VM2_MEMORY_MB} DUAL_VM3_MEMORY_MB=${DUAL_VM3_MEMORY_MB} DUAL_VM4_MEMORY_MB=${DUAL_VM4_MEMORY_MB} \
	DUAL_VM1_VCPUS=${DUAL_VM1_VCPUS} DUAL_VM2_VCPUS=${DUAL_VM2_VCPUS} DUAL_VM3_VCPUS=${DUAL_VM3_VCPUS} DUAL_VM4_VCPUS=${DUAL_VM4_VCPUS} \
	${DUAL_VM_SCRIPT} start vm3

dual-vm4:
	LINUX_DIR=${LINUX} RUNTIME_IMAGE=$(RUNTIME_IMAGE) \
	DUAL_VM1_SSH_PORT=${DUAL_VM1_SSH_PORT} DUAL_VM1_NET_PORT=${DUAL_VM1_NET_PORT} DUAL_VM1_GDB_PORT=${DUAL_VM1_GDB_PORT} \
	DUAL_VM2_SSH_PORT=${DUAL_VM2_SSH_PORT} DUAL_VM2_NET_PORT=${DUAL_VM2_NET_PORT} DUAL_VM2_GDB_PORT=${DUAL_VM2_GDB_PORT} \
	DUAL_VM3_SSH_PORT=${DUAL_VM3_SSH_PORT} DUAL_VM3_NET_PORT=${DUAL_VM3_NET_PORT} DUAL_VM3_GDB_PORT=${DUAL_VM3_GDB_PORT} \
	DUAL_VM4_SSH_PORT=${DUAL_VM4_SSH_PORT} DUAL_VM4_NET_PORT=${DUAL_VM4_NET_PORT} DUAL_VM4_GDB_PORT=${DUAL_VM4_GDB_PORT} \
	DUAL_VM1_HOST_CPUSET=${DUAL_VM1_HOST_CPUSET} DUAL_VM2_HOST_CPUSET=${DUAL_VM2_HOST_CPUSET} DUAL_VM3_HOST_CPUSET=${DUAL_VM3_HOST_CPUSET} DUAL_VM4_HOST_CPUSET=${DUAL_VM4_HOST_CPUSET} \
	DUAL_VM1_MEMORY_MB=${DUAL_VM1_MEMORY_MB} DUAL_VM2_MEMORY_MB=${DUAL_VM2_MEMORY_MB} DUAL_VM3_MEMORY_MB=${DUAL_VM3_MEMORY_MB} DUAL_VM4_MEMORY_MB=${DUAL_VM4_MEMORY_MB} \
	DUAL_VM1_VCPUS=${DUAL_VM1_VCPUS} DUAL_VM2_VCPUS=${DUAL_VM2_VCPUS} DUAL_VM3_VCPUS=${DUAL_VM3_VCPUS} DUAL_VM4_VCPUS=${DUAL_VM4_VCPUS} \
	${DUAL_VM_SCRIPT} start vm4

dual-vm1-ssh:
	LINUX_DIR=${LINUX} RUNTIME_IMAGE=$(RUNTIME_IMAGE) \
	DUAL_VM1_SSH_PORT=${DUAL_VM1_SSH_PORT} DUAL_VM2_SSH_PORT=${DUAL_VM2_SSH_PORT} DUAL_VM3_SSH_PORT=${DUAL_VM3_SSH_PORT} DUAL_VM4_SSH_PORT=${DUAL_VM4_SSH_PORT} \
	${DUAL_VM_SCRIPT} ssh vm1

dual-vm2-ssh:
	LINUX_DIR=${LINUX} RUNTIME_IMAGE=$(RUNTIME_IMAGE) \
	DUAL_VM1_SSH_PORT=${DUAL_VM1_SSH_PORT} DUAL_VM2_SSH_PORT=${DUAL_VM2_SSH_PORT} DUAL_VM3_SSH_PORT=${DUAL_VM3_SSH_PORT} DUAL_VM4_SSH_PORT=${DUAL_VM4_SSH_PORT} \
	${DUAL_VM_SCRIPT} ssh vm2

dual-vm3-ssh:
	LINUX_DIR=${LINUX} RUNTIME_IMAGE=$(RUNTIME_IMAGE) \
	DUAL_VM1_SSH_PORT=${DUAL_VM1_SSH_PORT} DUAL_VM2_SSH_PORT=${DUAL_VM2_SSH_PORT} DUAL_VM3_SSH_PORT=${DUAL_VM3_SSH_PORT} DUAL_VM4_SSH_PORT=${DUAL_VM4_SSH_PORT} \
	${DUAL_VM_SCRIPT} ssh vm3

dual-vm4-ssh:
	LINUX_DIR=${LINUX} RUNTIME_IMAGE=$(RUNTIME_IMAGE) \
	DUAL_VM1_SSH_PORT=${DUAL_VM1_SSH_PORT} DUAL_VM2_SSH_PORT=${DUAL_VM2_SSH_PORT} DUAL_VM3_SSH_PORT=${DUAL_VM3_SSH_PORT} DUAL_VM4_SSH_PORT=${DUAL_VM4_SSH_PORT} \
	${DUAL_VM_SCRIPT} ssh vm4

dual-vm-status:
	LINUX_DIR=${LINUX} RUNTIME_IMAGE=$(RUNTIME_IMAGE) \
	DUAL_VM1_SSH_PORT=${DUAL_VM1_SSH_PORT} DUAL_VM2_SSH_PORT=${DUAL_VM2_SSH_PORT} DUAL_VM3_SSH_PORT=${DUAL_VM3_SSH_PORT} DUAL_VM4_SSH_PORT=${DUAL_VM4_SSH_PORT} \
	${DUAL_VM_SCRIPT} status

dual-vm-stop:
	LINUX_DIR=${LINUX} RUNTIME_IMAGE=$(RUNTIME_IMAGE) \
	DUAL_VM1_SSH_PORT=${DUAL_VM1_SSH_PORT} DUAL_VM1_NET_PORT=${DUAL_VM1_NET_PORT} DUAL_VM1_GDB_PORT=${DUAL_VM1_GDB_PORT} \
	DUAL_VM2_SSH_PORT=${DUAL_VM2_SSH_PORT} DUAL_VM2_NET_PORT=${DUAL_VM2_NET_PORT} DUAL_VM2_GDB_PORT=${DUAL_VM2_GDB_PORT} \
	DUAL_VM3_SSH_PORT=${DUAL_VM3_SSH_PORT} DUAL_VM3_NET_PORT=${DUAL_VM3_NET_PORT} DUAL_VM3_GDB_PORT=${DUAL_VM3_GDB_PORT} \
	DUAL_VM4_SSH_PORT=${DUAL_VM4_SSH_PORT} DUAL_VM4_NET_PORT=${DUAL_VM4_NET_PORT} DUAL_VM4_GDB_PORT=${DUAL_VM4_GDB_PORT} \
	DUAL_VM1_HOST_CPUSET=${DUAL_VM1_HOST_CPUSET} DUAL_VM2_HOST_CPUSET=${DUAL_VM2_HOST_CPUSET} DUAL_VM3_HOST_CPUSET=${DUAL_VM3_HOST_CPUSET} DUAL_VM4_HOST_CPUSET=${DUAL_VM4_HOST_CPUSET} \
	DUAL_VM1_MEMORY_MB=${DUAL_VM1_MEMORY_MB} DUAL_VM2_MEMORY_MB=${DUAL_VM2_MEMORY_MB} DUAL_VM3_MEMORY_MB=${DUAL_VM3_MEMORY_MB} DUAL_VM4_MEMORY_MB=${DUAL_VM4_MEMORY_MB} \
	DUAL_VM1_VCPUS=${DUAL_VM1_VCPUS} DUAL_VM2_VCPUS=${DUAL_VM2_VCPUS} DUAL_VM3_VCPUS=${DUAL_VM3_VCPUS} DUAL_VM4_VCPUS=${DUAL_VM4_VCPUS} \
	${DUAL_VM_SCRIPT} stop all

vmlinux:
	KTRACK_KERNEL_DIR=${LINUX} ${KTRACK} auto-checkpoint --label vmlinux
	docker run --rm -v ${LINUX}:/linux -w /linux $(RUNTIME_IMAGE) make -j`nproc` bzImage 

headers-install:
	KTRACK_KERNEL_DIR=${LINUX} ${KTRACK} auto-checkpoint --label headers-install
	docker run --rm -v ${LINUX}:/linux -w /linux $(RUNTIME_IMAGE) make -j`nproc` headers_install 

modules-install:
	KTRACK_KERNEL_DIR=${LINUX} ${KTRACK} auto-checkpoint --label modules-install
	docker run --rm -v ${LINUX}:/linux -w /linux $(RUNTIME_IMAGE) make -j`nproc` modules
	docker run --rm -v ${LINUX}:/linux -w /linux $(RUNTIME_IMAGE) make -j`nproc` modules_install

kernel:
	KTRACK_KERNEL_DIR=${LINUX} ${KTRACK} auto-checkpoint --label kernel
	docker run --rm -v ${LINUX}:/linux -w /linux $(RUNTIME_IMAGE) make -j`nproc` 

linux-clean:
	docker run --rm -v ${LINUX}:/linux -w /linux $(RUNTIME_IMAGE) make distclean

enter-docker:
	docker run --rm -v ${BASE_PROJ}:/linux-dev-env -w /linux-dev-env -it $(RUNTIME_IMAGE) /bin/bash

libbpf:
	docker run --rm -v ${LINUX}:/linux -w /linux/tools/lib/bpf $(RUNTIME_IMAGE) make -j`nproc`

libbpf-clean:
	docker run --rm -v ${LINUX}:/linux -w /linux/tools/lib/bpf $(RUNTIME_IMAGE) make clean -j`nproc`

bpftool:
	docker run --rm -v ${LINUX}:/linux -w /linux/tools/bpf/bpftool $(RUNTIME_IMAGE) make -j`nproc`

bpftool-clean:
	docker run --rm -v ${LINUX}:/linux -w /linux/tools/bpf/bpftool $(RUNTIME_IMAGE) make clean -j`nproc`

ktrack-status:
	KTRACK_KERNEL_DIR=${LINUX} ${KTRACK} status

ktrack-list:
	KTRACK_KERNEL_DIR=${LINUX} ${KTRACK} list

ktrack-checkpoint:
	KTRACK_KERNEL_DIR=${LINUX} ${KTRACK} checkpoint --label manual

test-ktrack:
	./tools/kernel-track/tests/run.sh

test-vm-dev:
	./tests/vm-linux-dev/run.sh

exp1-katran-build:
	EXP1_KATRAN_FORCE_REBUILD="$(EXP1_KATRAN_FORCE_REBUILD)" \
	EXP1_KATRAN_INSTALL_BUILD_DEPS="$(EXP1_KATRAN_INSTALL_BUILD_DEPS)" \
	${EXP1_KATRAN_BUILD_SCRIPT}

exp1-run:
	DUAL_VM1_HOST_CPUSET="$(DUAL_VM1_HOST_CPUSET)" \
	DUAL_VM2_HOST_CPUSET="$(DUAL_VM2_HOST_CPUSET)" \
	DUAL_VM3_HOST_CPUSET="$(DUAL_VM3_HOST_CPUSET)" \
	DUAL_VM4_HOST_CPUSET="$(DUAL_VM4_HOST_CPUSET)" \
	DUAL_VM1_MEMORY_MB="$(DUAL_VM1_MEMORY_MB)" \
	DUAL_VM2_MEMORY_MB="$(DUAL_VM2_MEMORY_MB)" \
	DUAL_VM3_MEMORY_MB="$(DUAL_VM3_MEMORY_MB)" \
	DUAL_VM4_MEMORY_MB="$(DUAL_VM4_MEMORY_MB)" \
	DUAL_VM1_VCPUS="$(DUAL_VM1_VCPUS)" \
	DUAL_VM2_VCPUS="$(DUAL_VM2_VCPUS)" \
	DUAL_VM3_VCPUS="$(DUAL_VM3_VCPUS)" \
	DUAL_VM4_VCPUS="$(DUAL_VM4_VCPUS)" \
	EXP1_MODE="$(EXP1_MODE)" \
	EXP1_WORKLOADS="$(EXP1_WORKLOADS)" \
	EXP1_WRK_CONNECTIONS="$(EXP1_WRK_CONNECTIONS)" \
	EXP1_WRK_THREADS="$(EXP1_WRK_THREADS)" \
	EXP1_WRK_WARMUP="$(EXP1_WRK_WARMUP)" \
	EXP1_WRK_DURATION="$(EXP1_WRK_DURATION)" \
	EXP1_WRK_REPEATS="$(EXP1_WRK_REPEATS)" \
	EXP1_NGINX_CPUSET="$(EXP1_NGINX_CPUSET)" \
	EXP1_WRK_CPUSET="$(EXP1_WRK_CPUSET)" \
	EXP1_WRK2_RATES="$(EXP1_WRK2_RATES)" \
	EXP1_WRK2_THREADS="$(EXP1_WRK2_THREADS)" \
	EXP1_WRK2_CONNECTIONS="$(EXP1_WRK2_CONNECTIONS)" \
	EXP1_WRK2_WARMUP="$(EXP1_WRK2_WARMUP)" \
	EXP1_WRK2_DURATION="$(EXP1_WRK2_DURATION)" \
	EXP1_WRK2_REPEATS="$(EXP1_WRK2_REPEATS)" \
	EXP1_WRK2_CPUSET="$(EXP1_WRK2_CPUSET)" \
	EXP1_WRK2_BIN="$(EXP1_WRK2_BIN)" \
	EXP1_WRK2_AUTO_BUILD="$(EXP1_WRK2_AUTO_BUILD)" \
	EXP1_HTTPERF_CPUSET="$(EXP1_HTTPERF_CPUSET)" \
	EXP1_HTTPERF_RATES="$(EXP1_HTTPERF_RATES)" \
	EXP1_HTTPERF_WARMUP="$(EXP1_HTTPERF_WARMUP)" \
	EXP1_HTTPERF_DURATION="$(EXP1_HTTPERF_DURATION)" \
	EXP1_HTTPERF_REPEATS="$(EXP1_HTTPERF_REPEATS)" \
	EXP1_HTTPERF_TIMEOUT="$(EXP1_HTTPERF_TIMEOUT)" \
	EXP1_HTTPERF_CLIENT_VMS="$(EXP1_HTTPERF_CLIENT_VMS)" \
	EXP1_HTTPERF_WORKERS_PER_VM="$(EXP1_HTTPERF_WORKERS_PER_VM)" \
	EXP1_HTTPERF_ULIMIT_NOFILE="$(EXP1_HTTPERF_ULIMIT_NOFILE)" \
	EXP1_KATRAN_CPUSET="$(EXP1_KATRAN_CPUSET)" \
	EXP1_KATRAN_VIP="$(EXP1_KATRAN_VIP)" \
	EXP1_KATRAN_GRPC_PORT="$(EXP1_KATRAN_GRPC_PORT)" \
	EXP1_KATRAN_DEFAULT_MAC="$(EXP1_KATRAN_DEFAULT_MAC)" \
	EXP1_KATRAN_FORWARDING_CORES="$(EXP1_KATRAN_FORWARDING_CORES)" \
	EXP1_KATRAN_LRU_SIZE="$(EXP1_KATRAN_LRU_SIZE)" \
	EXP1_KATRAN_SERVER_BIN="$(EXP1_KATRAN_SERVER_BIN)" \
	EXP1_KATRAN_BPF_OBJ="$(EXP1_KATRAN_BPF_OBJ)" \
		EXP1_KATRAN_GOCLIENT_BIN="$(EXP1_KATRAN_GOCLIENT_BIN)" \
		EXP1_KATRAN_LIB_DIRS="$(EXP1_KATRAN_LIB_DIRS)" \
		EXP1_KATRAN_AUTO_BUILD="$(EXP1_KATRAN_AUTO_BUILD)" \
		EXP1_KATRAN_REQUIRED_BPF_DEFINE="$(EXP1_KATRAN_REQUIRED_BPF_DEFINE)" \
		EXP1_KATRAN_LOCAL_DELIVERY_FLAGS="$(EXP1_KATRAN_LOCAL_DELIVERY_FLAGS)" \
		${EXP1_SCRIPT_DIR}/run.sh

exp1-smoke:
	DUAL_VM1_HOST_CPUSET="$(DUAL_VM1_HOST_CPUSET)" \
	DUAL_VM2_HOST_CPUSET="$(DUAL_VM2_HOST_CPUSET)" \
	DUAL_VM3_HOST_CPUSET="$(DUAL_VM3_HOST_CPUSET)" \
	DUAL_VM4_HOST_CPUSET="$(DUAL_VM4_HOST_CPUSET)" \
	DUAL_VM1_MEMORY_MB="$(DUAL_VM1_MEMORY_MB)" \
	DUAL_VM2_MEMORY_MB="$(DUAL_VM2_MEMORY_MB)" \
	DUAL_VM3_MEMORY_MB="$(DUAL_VM3_MEMORY_MB)" \
	DUAL_VM4_MEMORY_MB="$(DUAL_VM4_MEMORY_MB)" \
	DUAL_VM1_VCPUS="$(DUAL_VM1_VCPUS)" \
	DUAL_VM2_VCPUS="$(DUAL_VM2_VCPUS)" \
	DUAL_VM3_VCPUS="$(DUAL_VM3_VCPUS)" \
	DUAL_VM4_VCPUS="$(DUAL_VM4_VCPUS)" \
	EXP1_MODE="direct" \
	EXP1_WORKLOADS="wrk" \
	EXP1_WRK_THREADS="1" \
	EXP1_WRK_CONNECTIONS="1 2" \
	EXP1_WRK_WARMUP="2" \
	EXP1_WRK_DURATION="4" \
	EXP1_WRK_REPEATS="1" \
	EXP1_NGINX_CPUSET="$(EXP1_NGINX_CPUSET)" \
	EXP1_WRK_CPUSET="$(EXP1_WRK_CPUSET)" \
	${EXP1_SCRIPT_DIR}/run.sh

exp1-plot:
	@if [ -z "$(EXP1_RUN_DIR)" ]; then \
		echo "set EXP1_RUN_DIR=results/exp1/<run-id>-<direct-nginx|vanilla-katran>"; \
		exit 1; \
	fi
	MPLCONFIGDIR=/tmp/mplconfig-exp1 python3 ${EXP1_SCRIPT_DIR}/plot.py --run-dir "$(EXP1_RUN_DIR)"

exp2-discover:
	@for wl in $(EXP2_STAGEA_WORKLOADS); do \
		echo "[exp2-discover] running stageA for workload=$$wl maps=$(EXP2_STAGEA_MAPS)"; \
		DUAL_VM1_SSH_PORT=$(DUAL_VM1_SSH_PORT) \
		DUAL_VM2_SSH_PORT=$(DUAL_VM2_SSH_PORT) \
		EXP2_RESULTS_BASE="$(EXP2_RESULTS_BASE)" \
		EXP2_STAGEA_WORKLOAD="$$wl" \
		EXP2_STAGEA_WRK_CONNECTIONS="$(EXP2_STAGEA_WRK_CONNECTIONS)" \
		EXP2_STAGEA_WRK_THREADS="$(EXP2_STAGEA_WRK_THREADS)" \
		EXP2_STAGEA_WRK2_RATE="$(EXP2_STAGEA_WRK2_RATE)" \
		EXP2_STAGEA_WRK2_CONNECTIONS="$(EXP2_STAGEA_WRK2_CONNECTIONS)" \
		EXP2_STAGEA_WRK2_THREADS="$(EXP2_STAGEA_WRK2_THREADS)" \
		EXP2_STAGEA_WORKLOAD_WARMUP_SECS="$(EXP2_STAGEA_WORKLOAD_WARMUP_SECS)" \
		EXP2_STAGEA_MEASURE_TAIL_SECS="$(EXP2_STAGEA_MEASURE_TAIL_SECS)" \
		EXP2_STAGEA_STEADY_WARMUP_SECS="$(EXP2_STAGEA_STEADY_WARMUP_SECS)" \
		EXP2_STAGEA_SAMPLE_INTERVAL_SECS="$(EXP2_STAGEA_SAMPLE_INTERVAL_SECS)" \
		EXP2_STAGEA_SAMPLE_COUNT="$(EXP2_STAGEA_SAMPLE_COUNT)" \
		EXP2_STAGEA_MAPS="$(EXP2_STAGEA_MAPS)" \
		EXP2_STAGEA_BALANCER_PROG_NAME="$(EXP2_STAGEA_BALANCER_PROG_NAME)" \
		EXP2_STAGEA_MAX_MAP_DUMP_ENTRIES="$(EXP2_STAGEA_MAX_MAP_DUMP_ENTRIES)" \
		EXP2_STAGEA_SKIP_LARGE_MAP_DUMPS="$(EXP2_STAGEA_SKIP_LARGE_MAP_DUMPS)" \
		EXP2_STAGEA_KEEP_INVARIANT_HASH_ONLY_DUMP="$(EXP2_STAGEA_KEEP_INVARIANT_HASH_ONLY_DUMP)" \
		EXP2_STAGEA_SKIP_INSTALL="$(EXP2_STAGEA_SKIP_INSTALL)" \
		${EXP2_SCRIPT_DIR}/discover.sh || exit $$?; \
	done

exp2-oracle-build:
	EXP2_RESULTS_BASE="$(EXP2_RESULTS_BASE)" \
	EXP2_ORACLE_RESULTS_BASE="$(EXP2_ORACLE_RESULTS_BASE)" \
	EXP2_ORACLE_SPEC="$(EXP2_ORACLE_SPEC)" \
	EXP2_ORACLE_RING_SIZE="$(EXP2_ORACLE_RING_SIZE)" \
	EXP2_ORACLE_GENERATED_HEADER="$(EXP2_ORACLE_GENERATED_HEADER)" \
	EXP2_ORACLE_KATRAN_SRC_DIR="$(EXP2_ORACLE_KATRAN_SRC_DIR)" \
	EXP2_ORACLE_KATRAN_BUILD_DIR="$(EXP2_ORACLE_KATRAN_BUILD_DIR)" \
	EXP2_ORACLE_BPF_DEFINES="$(EXP2_ORACLE_BPF_DEFINES)" \
	EXP2_ORACLE_FORCE_REBUILD="$(EXP2_ORACLE_FORCE_REBUILD)" \
	EXP2_ORACLE_SKIP_BUILD="$(EXP2_ORACLE_SKIP_BUILD)" \
	${EXP2_SCRIPT_DIR}/build-oracle.sh

exp2-eval:
	EXP2_EVAL_RESULTS_BASE="$(EXP2_EVAL_RESULTS_BASE)" \
	EXP2_ORACLE_RESULTS_BASE="$(EXP2_ORACLE_RESULTS_BASE)" \
	EXP2_EVAL_ORACLE_ENV="$(EXP2_EVAL_ORACLE_ENV)" \
	EXP2_EVAL_RUN_ID="$(EXP2_EVAL_RUN_ID)" \
	EXP2_EVAL_ARCHIVE_OLD="$(EXP2_EVAL_ARCHIVE_OLD)" \
	EXP2_EVAL_VANILLA_KATRAN_AUTO_BUILD="$(EXP2_EVAL_VANILLA_KATRAN_AUTO_BUILD)" \
	EXP2_EVAL_OPT_KATRAN_AUTO_BUILD="$(EXP2_EVAL_OPT_KATRAN_AUTO_BUILD)" \
	${EXP2_SCRIPT_DIR}/eval.sh

exp2-eval-four-set:
	EXP2_EVAL4_RESULTS_BASE="$(EXP2_EVAL4_RESULTS_BASE)" \
	EXP2_ORACLE_RESULTS_BASE="$(EXP2_ORACLE_RESULTS_BASE)" \
	EXP2_EVAL4_ORACLE_ENV="$(EXP2_EVAL4_ORACLE_ENV)" \
	EXP2_EVAL4_RUN_ID="$(EXP2_EVAL4_RUN_ID)" \
	EXP2_EVAL4_ARCHIVE_OLD="$(EXP2_EVAL4_ARCHIVE_OLD)" \
	EXP2_EVAL4_VANILLA_KATRAN_AUTO_BUILD="$(EXP2_EVAL4_VANILLA_KATRAN_AUTO_BUILD)" \
	EXP2_EVAL4_OPT_KATRAN_AUTO_BUILD="$(EXP2_EVAL4_OPT_KATRAN_AUTO_BUILD)" \
	EXP2_EVAL4_CLIENT_VM="$(EXP2_EVAL4_CLIENT_VM)" \
	EXP2_EVAL4_LB_VM="$(EXP2_EVAL4_LB_VM)" \
	EXP2_EVAL4_BACKEND_VM="$(EXP2_EVAL4_BACKEND_VM)" \
	EXP2_EVAL4_BACKEND_IP="$(EXP2_EVAL4_BACKEND_IP)" \
	EXP2_EVAL4_FORWARD_VIP="$(EXP2_EVAL4_FORWARD_VIP)" \
	EXP2_EVAL4_KATRAN_VIP="$(EXP2_EVAL4_KATRAN_VIP)" \
	EXP2_EVAL4_KATRAN_DEFAULT_MAC="$(EXP2_EVAL4_KATRAN_DEFAULT_MAC)" \
	${EXP2_SCRIPT_DIR}/eval-four-set.sh

test:
	./tests/run.sh
